language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
script: "bundle exec rspec"
cache: bundler
notifications:
  email:
    recipients:
      - kigster@gmail.com
    on_success: never
    on_change: always
