---
:date: '2017-05-18 02:22:49 -0700'
:pricing:
  :g3-standard-8-smartos:
    :cost: 0.26
    :ram: 8.0
    :cpus: 4.0
    :disk: 738
  :g3-highcpu-8-smartos:
    :cost: 0.58
    :ram: 8.0
    :cpus: 8.0
    :disk: 738
  :g3-standard-0.5-smartos:
    :cost: 0.016
    :ram: 0.5
    :cpus: 0.5
  :g3-highmemory-96-smartos:
    :cost: 2.451
    :ram: 7.5
    :cpus: 32.0
    :disk: 3100
  :g3-standard-0.625-smartos:
    :name: g3-standard-0.625-smartos
    :os: smartos
    :cost: 0.02
    :cpus: 0.15
    :disk: 20
    :ram: 0.625
  :g3-standard-1.75-smartos:
    :name: g3-standard-1.75-smartos
    :os: smartos
    :cost: 0.056
    :cpus: 1.0
    :disk: 56
    :ram: 1.75
  :g3-standard-3.75-smartos:
    :name: g3-standard-3.75-smartos
    :os: smartos
    :cost: 0.12
    :cpus: 1.0
    :disk: 123
    :ram: 3.75
  :g3-standard-7.5-smartos:
    :name: g3-standard-7.5-smartos
    :os: smartos
    :cost: 0.24
    :cpus: 2.0
    :disk: 738
    :ram: 7.5
  :g3-standard-15-smartos:
    :name: g3-standard-15-smartos
    :os: smartos
    :cost: 0.48
    :cpus: 4.0
    :disk: 1467
    :ram: 15.0
  :g3-standard-30-smartos:
    :name: g3-standard-30-smartos
    :os: smartos
    :cost: 0.96
    :cpus: 8.0
    :disk: 1683
    :ram: 30.0
  :g3-standard-48-smartos:
    :name: g3-standard-48-smartos
    :os: smartos
    :cost: 1.536
    :cpus: 12.0
    :disk: 1683
    :ram: 48.0
  :g3-standard-64-smartos:
    :name: g3-standard-64-smartos
    :os: smartos
    :cost: 2.048
    :cpus: 16.0
    :disk: 2100
    :ram: 64.0
  :g3-standard-80-smartos:
    :name: g3-standard-80-smartos
    :os: smartos
    :cost: 2.56
    :cpus: 20.0
    :disk: 2625
    :ram: 80.0
  :g3-standard-96-smartos:
    :name: g3-standard-96-smartos
    :os: smartos
    :cost: 3.072
    :cpus: 24.0
    :disk: 3150
    :ram: 96.0
  :g3-standard-128-smartos-cc:
    :name: g3-standard-128-smartos-cc
    :os: smartos
    :cost: 4.096
    :cpus: 32.0
    :disk: 4200
    :ram: 128.0
  :g3-highmemory-17.125-smartos:
    :name: g3-highmemory-17.125-smartos
    :os: smartos
    :cost: 0.409
    :cpus: 2.0
    :disk: 420
    :ram: 17.125
  :g3-highmemory-34.25-smartos:
    :name: g3-highmemory-34.25-smartos
    :os: smartos
    :cost: 0.817
    :cpus: 4.0
    :disk: 843
    :ram: 34.25
  :g3-highmemory-68.375-smartos:
    :name: g3-highmemory-68.375-smartos
    :os: smartos
    :cost: 1.63
    :cpus: 8.0
    :disk: 1122
    :ram: 68.375
  :g3-highmemory-144-smartos:
    :name: g3-highmemory-144-smartos
    :os: smartos
    :cost: 3.433
    :cpus: 18.0
    :disk: 2363
    :ram: 144.0
  :g3-highmemory-256-smartos-cc:
    :name: g3-highmemory-256-smartos-cc
    :os: smartos
    :cost: 6.102
    :cpus: 32.0
    :disk: 4200
    :ram: 256.0
  :g3-highcpu-1.75-smartos:
    :name: g3-highcpu-1.75-smartos
    :os: smartos
    :cost: 0.127
    :cpus: 2.0
    :disk: 75
    :ram: 1.75
  :g3-highcpu-7-smartos:
    :name: g3-highcpu-7-smartos
    :os: smartos
    :cost: 0.508
    :cpus: 7.0
    :disk: 262
    :ram: 7.0
  :g3-highcpu-16-smartos:
    :name: g3-highcpu-16-smartos
    :os: smartos
    :cost: 1.16
    :cpus: 16.0
    :disk: 600
    :ram: 16.0
  :g3-highcpu-24-smartos:
    :name: g3-highcpu-24-smartos
    :os: smartos
    :cost: 1.739
    :cpus: 24.0
    :disk: 900
    :ram: 24.0
  :g3-highcpu-32-smartos-cc:
    :name: g3-highcpu-32-smartos-cc
    :os: smartos
    :cost: 2.319
    :cpus: 32.0
    :disk: 1200
    :ram: 32.0
  :g3-highio-15-smartos:
    :name: g3-highio-15-smartos
    :os: smartos
    :cost: 0.76
    :cpus: 2.0
    :disk: 360
    :ram: 15.0
  :g3-highio-30-smartos:
    :name: g3-highio-30-smartos
    :os: smartos
    :cost: 1.52
    :cpus: 4.0
    :disk: 725
    :ram: 30.0
  :g3-highio-60.5-smartos:
    :name: g3-highio-60.5-smartos
    :os: smartos
    :cost: 3.067
    :cpus: 8.0
    :disk: 1452
    :ram: 60.5
  :g3-highio-128-smartos:
    :name: g3-highio-128-smartos
    :os: smartos
    :cost: 6.488
    :cpus: 16.0
    :disk: 3072
    :ram: 128.0
  :g3-highio-256-smartos-cc:
    :name: g3-highio-256-smartos-cc
    :os: smartos
    :cost: 12.976
    :cpus: 32.0
    :disk: 6144
    :ram: 256.0
  :g3-highstorage-32-smartos:
    :name: g3-highstorage-32-smartos
    :os: smartos
    :cost: 0.863
    :cpus: 8.0
    :disk: 7680
    :ram: 32.0
  :g3-highstorage-64-smartos:
    :name: g3-highstorage-64-smartos
    :os: smartos
    :cost: 1.726
    :cpus: 16.0
    :disk: 15360
    :ram: 64.0
  :g3-highstorage-128-smartos-cc:
    :name: g3-highstorage-128-smartos-cc
    :os: smartos
    :cost: 3.451
    :cpus: 32.0
    :disk: 30720
    :ram: 128.0
  :g3-standard-0.625-kvm:
    :name: g3-standard-0.625-kvm
    :os: Linux
    :cost: 0.02
    :cpus: 0.15
    :disk: 20
    :ram: 0.625
  :g3-standard-1.75-kvm:
    :name: g3-standard-1.75-kvm
    :os: Linux
    :cost: 0.056
    :cpus: 1.0
    :disk: 56
    :ram: 1.75
  :g3-standard-3.75-kvm:
    :name: g3-standard-3.75-kvm
    :os: Linux
    :cost: 0.12
    :cpus: 1.0
    :disk: 123
    :ram: 3.75
  :g3-standard-7.5-kvm:
    :name: g3-standard-7.5-kvm
    :os: Linux
    :cost: 0.24
    :cpus: 2.0
    :disk: 738
    :ram: 7.5
  :g3-standard-15-kvm:
    :name: g3-standard-15-kvm
    :os: Linux
    :cost: 0.48
    :cpus: 4.0
    :disk: 1467
    :ram: 15.0
  :g3-standard-30-kvm:
    :name: g3-standard-30-kvm
    :os: Linux
    :cost: 0.96
    :cpus: 8.0
    :disk: 1683
    :ram: 30.0
  :g3-highmemory-17.125-kvm:
    :name: g3-highmemory-17.125-kvm
    :os: Linux
    :cost: 0.409
    :cpus: 2.0
    :disk: 420
    :ram: 17.125
  :g3-highmemory-34.25-kvm:
    :name: g3-highmemory-34.25-kvm
    :os: Linux
    :cost: 0.817
    :cpus: 4.0
    :disk: 843
    :ram: 34.25
  :g3-highmemory-68.375-kvm:
    :name: g3-highmemory-68.375-kvm
    :os: Linux
    :cost: 1.63
    :cpus: 8.0
    :disk: 1122
    :ram: 68.375
  :g3-highcpu-1.75-kvm:
    :name: g3-highcpu-1.75-kvm
    :os: Linux
    :cost: 0.127
    :cpus: 2.0
    :disk: 75
    :ram: 1.75
  :g3-highcpu-7-kvm:
    :name: g3-highcpu-7-kvm
    :os: Linux
    :cost: 0.508
    :cpus: 7.0
    :disk: 262
    :ram: 7.0
  :g3-highio-15-kvm:
    :name: g3-highio-15-kvm
    :os: Linux
    :cost: 0.76
    :cpus: 2.0
    :disk: 360
    :ram: 15.0
  :g3-highio-30-kvm:
    :name: g3-highio-30-kvm
    :os: Linux
    :cost: 1.52
    :cpus: 4.0
    :disk: 725
    :ram: 30.0
  :g3-highio-60.5-kvm:
    :name: g3-highio-60.5-kvm
    :os: Linux
    :cost: 3.067
    :cpus: 8.0
    :disk: 1452
    :ram: 60.5
  :g3-highstorage-32-kvm:
    :name: g3-highstorage-32-kvm
    :os: Linux
    :cost: 0.863
    :cpus: 8.0
    :disk: 7680
    :ram: 32.0
  :t4-standard-128M:
    :name: t4-standard-128M
    :os: Infrastructure Container
    :cost: 0.003
    :cpus: 0.0625
    :disk: 3
    :ram: 0.128
  :t4-standard-256M:
    :name: t4-standard-256M
    :os: Infrastructure Container
    :cost: 0.007
    :cpus: 0.125
    :disk: 6
    :ram: 0.256
  :t4-standard-512M:
    :name: t4-standard-512M
    :os: Infrastructure Container
    :cost: 0.013
    :cpus: 0.25
    :disk: 12
    :ram: 0.512
  :t4-standard-1G:
    :name: t4-standard-1G
    :os: Infrastructure Container
    :cost: 0.026
    :cpus: 0.5
    :disk: 25
    :ram: 1.0
  :t4-standard-2G:
    :name: t4-standard-2G
    :os: Infrastructure Container
    :cost: 0.053
    :cpus: 1.0
    :disk: 50
    :ram: 2.0
  :t4-standard-4G:
    :name: t4-standard-4G
    :os: Infrastructure Container
    :cost: 0.105
    :cpus: 2.0
    :disk: 100
    :ram: 4.0
  :t4-standard-8G:
    :name: t4-standard-8G
    :os: Infrastructure Container
    :cost: 0.21
    :cpus: 4.0
    :disk: 200
    :ram: 8.0
  :t4-standard-16G:
    :name: t4-standard-16G
    :os: Infrastructure Container
    :cost: 0.42
    :cpus: 8.0
    :disk: 400
    :ram: 16.0
  :t4-standard-32G:
    :name: t4-standard-32G
    :os: Infrastructure Container
    :cost: 0.84
    :cpus: 16.0
    :disk: 800
    :ram: 32.0
  :t4-standard-64G:
    :name: t4-standard-64G
    :os: Infrastructure Container
    :cost: 1.68
    :cpus: 32.0
    :disk: 1600
    :ram: 64.0
  :g3-standard-1-kvm:
    :name: g3-standard-1-kvm
    :os: Hardware VM
    :cost: 0.032
    :cpus: 0.25
    :disk: 33
    :ram: 1.0
  :g3-standard-2-kvm:
    :name: g3-standard-2-kvm
    :os: Hardware VM
    :cost: 0.064
    :cpus: 1.0
    :disk: 66
    :ram: 2.0
  :g3-standard-4-kvm:
    :name: g3-standard-4-kvm
    :os: Hardware VM
    :cost: 0.128
    :cpus: 1.0
    :disk: 131
    :ram: 4.0
  :g3-highmemory-144-kvm:
    :name: g3-highmemory-144-kvm
    :os: Hardware VM
    :cost: 3.433
    :cpus: 18.0
    :disk: 2363
    :ram: 144.0
  :g3-highmemory-256-kvm-cc:
    :name: g3-highmemory-256-kvm-cc
    :os: Hardware VM
    :cost: 6.102
    :cpus: 32.0
    :disk: 4200
    :ram: 256.0
  :g3-highcpu-16-kvm:
    :name: g3-highcpu-16-kvm
    :os: Hardware VM
    :cost: 1.16
    :cpus: 16.0
    :disk: 600
    :ram: 16.0
  :g3-highcpu-24-kvm:
    :name: g3-highcpu-24-kvm
    :os: Hardware VM
    :cost: 1.739
    :cpus: 24.0
    :disk: 900
    :ram: 24.0
  :g3-highcpu-32-kvm-cc:
    :name: g3-highcpu-32-kvm-cc
    :os: Hardware VM
    :cost: 2.319
    :cpus: 32.0
    :disk: 1200
    :ram: 32.0
  :g3-highio-128-kvm:
    :name: g3-highio-128-kvm
    :os: Hardware VM
    :cost: 6.488
    :cpus: 16.0
    :disk: 3072
    :ram: 128.0
  :g3-highio-256-kvm-cc:
    :name: g3-highio-256-kvm-cc
    :os: Hardware VM
    :cost: 12.976
    :cpus: 32.0
    :disk: 6144
    :ram: 256.0
  :g4-highcpu-128M:
    :name: g4-highcpu-128M
    :os: smartos
    :cost: 0.003
    :cpus: 0.0625
    :disk: 2
    :ram: 0.125
    :monthly: 2.19
  :g4-highcpu-256M:
    :name: g4-highcpu-256M
    :os: smartos
    :cost: 0.007
    :cpus: 0.125
    :disk: 5
    :ram: 0.25
    :monthly: 5.11
  :g4-highcpu-512M:
    :name: g4-highcpu-512M
    :os: smartos
    :cost: 0.013
    :cpus: 0.25
    :disk: 10
    :ram: 0.5
    :monthly: 9.49
  :g4-highcpu-1G:
    :name: g4-highcpu-1G
    :os: smartos
    :cost: 0.026
    :cpus: 0.5
    :disk: 25
    :ram: 1.0
    :monthly: 18.98
  :g4-highcpu-2G:
    :name: g4-highcpu-2G
    :os: smartos
    :cost: 0.053
    :cpus: 1.0
    :disk: 50
    :ram: 2.0
    :monthly: 38.69
  :g4-highcpu-4G:
    :name: g4-highcpu-4G
    :os: smartos
    :cost: 0.105
    :cpus: 2.0
    :disk: 100
    :ram: 4.0
    :monthly: 76.65
  :g4-highcpu-8G:
    :name: g4-highcpu-8G
    :os: smartos
    :cost: 0.21
    :cpus: 4.0
    :disk: 200
    :ram: 8.0
    :monthly: 153.3
  :g4-highcpu-16G:
    :name: g4-highcpu-16G
    :os: smartos
    :cost: 0.42
    :cpus: 8.0
    :disk: 400
    :ram: 16.0
    :monthly: 306.6
  :g4-highcpu-32G:
    :name: g4-highcpu-32G
    :os: smartos
    :cost: 0.84
    :cpus: 16.0
    :disk: 800
    :ram: 32.0
    :monthly: 613.2
  :g4-highcpu-64G:
    :name: g4-highcpu-64G
    :os: smartos
    :cost: 1.68
    :cpus: 32.0
    :disk: 1600
    :ram: 64.0
    :monthly: 1226.4
  :g4-general-4G:
    :name: g4-general-4G
    :os: smartos
    :cost: 0.067
    :cpus: 1.0
    :disk: 50
    :ram: 4.0
    :monthly: 48.91
  :g4-general-8G:
    :name: g4-general-8G
    :os: smartos
    :cost: 0.133
    :cpus: 2.0
    :disk: 100
    :ram: 8.0
    :monthly: 97.09
  :g4-general-16G:
    :name: g4-general-16G
    :os: smartos
    :cost: 0.266
    :cpus: 4.0
    :disk: 200
    :ram: 16.0
    :monthly: 194.18
  :g4-general-32G:
    :name: g4-general-32G
    :os: smartos
    :cost: 0.532
    :cpus: 8.0
    :disk: 400
    :ram: 32.0
    :monthly: 388.36
  :g4-highram-16G:
    :name: g4-highram-16G
    :os: smartos
    :cost: 0.2075
    :cpus: 2.0
    :disk: 100
    :ram: 16.0
    :monthly: 151.48
  :g4-highram-32G:
    :name: g4-highram-32G
    :os: smartos
    :cost: 0.4163
    :cpus: 4.0
    :disk: 200
    :ram: 32.0
    :monthly: 303.9
  :g4-highram-64G:
    :name: g4-highram-64G
    :os: smartos
    :cost: 0.8313
    :cpus: 8.0
    :disk: 400
    :ram: 64.0
    :monthly: 606.85
  :g4-highram-110G:
    :name: g4-highram-110G
    :os: smartos
    :cost: 1.6625
    :cpus: 16.0
    :disk: 800
    :ram: 110.0
    :monthly: 1213.63
  :g4-fastdisk-32G:
    :name: g4-fastdisk-32G
    :os: smartos
    :cost: 0.853
    :cpus: 4.0
    :disk: 800
    :ram: 32.0
    :monthly: 622.69
  :g4-fastdisk-64G:
    :name: g4-fastdisk-64G
    :os: smartos
    :cost: 1.705
    :cpus: 8.0
    :disk: 1600
    :ram: 64.0
    :monthly: 1244.65
  :g4-fastdisk-110G:
    :name: g4-fastdisk-110G
    :os: smartos
    :cost: 3.41
    :cpus: 16.0
    :disk: 3200
    :ram: 110.0
    :monthly: 2489.3
  :g4-bigdisk-16G:
    :name: g4-bigdisk-16G
    :os: smartos
    :cost: 0.345
    :cpus: 2.0
    :disk: 1250
    :ram: 16.0
    :monthly: 251.85
  :g4-bigdisk-32G:
    :name: g4-bigdisk-32G
    :os: smartos
    :cost: 0.69
    :cpus: 4.0
    :disk: 2500
    :ram: 32.0
    :monthly: 503.7
  :g4-bigdisk-64G:
    :name: g4-bigdisk-64G
    :os: smartos
    :cost: 1.38
    :cpus: 8.0
    :disk: 5000
    :ram: 64.0
    :monthly: 1007.4
  :g4-bigdisk-110G:
    :name: g4-bigdisk-110G
    :os: smartos
    :cost: 2.76
    :cpus: 16.0
    :disk: 10000
    :ram: 110.0
    :monthly: 2014.8
  :k4-highcpu-kvm-250M:
    :name: k4-highcpu-kvm-250M
    :os: kvm
    :cost: 0.0163
    :cpus: 0.25
    :disk: 10
    :ram: 0.25
    :monthly: 11.9
  :k4-highcpu-kvm-750M:
    :name: k4-highcpu-kvm-750M
    :os: kvm
    :cost: 0.0325
    :cpus: 0.5
    :disk: 25
    :ram: 0.75
    :monthly: 23.73
  :k4-highcpu-kvm-1.75G:
    :name: k4-highcpu-kvm-1.75G
    :os: kvm
    :cost: 0.0663
    :cpus: 1.0
    :disk: 50
    :ram: 1.75
    :monthly: 48.4
  :k4-highcpu-kvm-3.75G:
    :name: k4-highcpu-kvm-3.75G
    :os: kvm
    :cost: 0.1313
    :cpus: 2.0
    :disk: 100
    :ram: 3.75
    :monthly: 95.85
  :k4-highcpu-kvm-7.75G:
    :name: k4-highcpu-kvm-7.75G
    :os: kvm
    :cost: 0.2625
    :cpus: 4.0
    :disk: 200
    :ram: 7.75
    :monthly: 191.63
  :k4-highcpu-kvm-15.75G:
    :name: k4-highcpu-kvm-15.75G
    :os: kvm
    :cost: 0.525
    :cpus: 8.0
    :disk: 400
    :ram: 15.75
    :monthly: 383.25
  :k4-general-kvm-3.75G:
    :name: k4-general-kvm-3.75G
    :os: kvm
    :cost: 0.0838
    :cpus: 1.0
    :disk: 50
    :ram: 3.75
    :monthly: 61.17
  :k4-general-kvm-7.75G:
    :name: k4-general-kvm-7.75G
    :os: kvm
    :cost: 0.1663
    :cpus: 2.0
    :disk: 100
    :ram: 7.75
    :monthly: 121.4
  :k4-general-kvm-15.75G:
    :name: k4-general-kvm-15.75G
    :os: kvm
    :cost: 0.3325
    :cpus: 4.0
    :disk: 200
    :ram: 15.75
    :monthly: 242.73
  :k4-general-kvm-31.75G:
    :name: k4-general-kvm-31.75G
    :os: kvm
    :cost: 0.665
    :cpus: 8.0
    :disk: 400
    :ram: 31.75
    :monthly: 485.45
  :k4-highram-kvm-15.75G:
    :name: k4-highram-kvm-15.75G
    :os: kvm
    :cost: 0.2594
    :cpus: 2.0
    :disk: 100
    :ram: 15.75
    :monthly: 189.36
  :k4-highram-kvm-31.75G:
    :name: k4-highram-kvm-31.75G
    :os: kvm
    :cost: 0.5203
    :cpus: 4.0
    :disk: 200
    :ram: 31.75
    :monthly: 379.82
  :k4-highram-kvm-63.75G:
    :name: k4-highram-kvm-63.75G
    :os: kvm
    :cost: 1.0391
    :cpus: 8.0
    :disk: 400
    :ram: 63.75
    :monthly: 758.54
  :k4-fastdisk-kvm-31.75G:
    :name: k4-fastdisk-kvm-31.75G
    :os: kvm
    :cost: 1.0663
    :cpus: 4.0
    :disk: 800
    :ram: 31.75
    :monthly: 778.4
  :k4-fastdisk-kvm-63.75G:
    :name: k4-fastdisk-kvm-63.75G
    :os: kvm
    :cost: 2.1313
    :cpus: 8.0
    :disk: 1600
    :ram: 63.75
    :monthly: 1555.85
  :k4-bigdisk-kvm-15.75G:
    :name: k4-bigdisk-kvm-15.75G
    :os: kvm
    :cost: 0.4125
    :cpus: 2.0
    :disk: 1200
    :ram: 15.75
    :monthly: 301.13
  :k4-bigdisk-kvm-31.75G:
    :name: k4-bigdisk-kvm-31.75G
    :os: kvm
    :cost: 0.825
    :cpus: 4.0
    :disk: 2500
    :ram: 31.75
    :monthly: 602.25
  :k4-bigdisk-kvm-63.75G:
    :name: k4-bigdisk-kvm-63.75G
    :os: kvm
    :cost: 1.725
    :cpus: 8.0
    :disk: 5000
    :ram: 63.75
    :monthly: 1259.25
